version: 2
jobs:
  build:
    working_directory: /spring-petclinic-microservices
    docker:
      - image: docker:17.11.0-ce
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image
          command: |
            pwd
            docker pull maven:3.5.3-jdk-8
            docker image ls
            # docker container run --rm -v "$(PWD)"/:/app -w /app -e DOCKER_HOST=unix:///var/run/docker.sock maven:3.5.3-jdk-8 mvn install -PbuildDocker -DskipTests
      - deploy:
          name: Push application Docker image
          command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1
            docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp:latest
            docker push $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/dockerapp:latest
