machine:
    java:
        version: openjdk8
general:
    artifacts:
        - "target/java-demo.war"
test:
    post:
        - mvn clean install
        - mvn clean install -PbuildDocker -DskipTests
      
      
